"""Deterministic scores from the blind judgments, plus the bar verdict and REPORT.md.

  bench/.venv/bin/python -m bench.score
"""
from __future__ import annotations

import json
import sys
from collections import Counter

from . import common

LOCAL = ("gemma-bigctx", "qwen-coder", "gemma-4-12b", "qwen3.5-9b")
CORE_BAR, INVENTED_BAR, P90_BAR = 0.90, 1, 180.0
CREDIT = {"hit": 1.0, "partial": 0.5, "miss": 0.0}


def percentile(values: list[float], p: float):
    vals = sorted(v for v in values if v is not None)
    if not vals:
        return None
    pos = (len(vals) - 1) * p
    lo, hi = int(pos), min(int(pos) + 1, len(vals) - 1)
    return round(vals[lo] + (vals[hi] - vals[lo]) * (pos - lo), 2)


def score_rep(entries: list[tuple[dict, dict, dict]]) -> dict:
    """entries: (key, grade, result row) for one contestant and one rep across meetings."""
    dec = act = q = 0.0
    n_dec = n_act = n_q = 0
    found_actions = owner_right = 0
    invented_dec = invented_act = supported = control_dec = unusable = 0
    traps = Counter()
    walls, models = [], []
    for key, grade, row in entries:
        trap_kind = {t["id"]: t["kind"] for t in key.get("traps", [])}
        for item in key.get("decisions", []):
            dec += CREDIT[grade["decisions"][item["id"]]]; n_dec += 1
        for item in key.get("actions", []):
            v = grade["actions"][item["id"]]
            act += CREDIT[v["found"]]; n_act += 1
            if v["found"] != "miss":
                found_actions += 1
                owner_right += v["owner"] == "right"
        for item in key.get("questions", []):
            q += CREDIT[grade["questions"][item["id"]]]; n_q += 1
        for x in grade["extras"]:
            bad = x["verdict"] in ("invented", "trap")
            # In a control meeting (no decisions made) a Decisions bullet is counted here for
            # visibility, but only what the judge marks invented or trap-fallen is penalized:
            # "parked for later" / "stays out of scope" are accurate non-decisions, not inventions.
            if x["section"] == "decisions" and key.get("control"):
                control_dec += 1
            if x["verdict"] == "trap" and x.get("trap") in trap_kind:
                traps[trap_kind[x["trap"]]] += 1
            if x["verdict"] == "supported" and not (x["section"] == "decisions" and key.get("control")):
                supported += 1
            if bad and x["section"] == "decisions":
                invented_dec += 1
            elif bad:
                invented_act += 1
        if row.get("status") != "ok" or not grade.get("format_ok"):
            unusable += 1
        walls.append(row.get("wall_s"))
        models.append(row.get("model_s"))
    ratio = lambda a, n: round(a / n, 4) if n else None
    return {
        "meetings": len(entries),
        "decision_recall": ratio(dec, n_dec), "action_recall": ratio(act, n_act),
        "core_recall": ratio(dec + act, n_dec + n_act), "question_recall": ratio(q, n_q),
        "owner_accuracy": ratio(owner_right, found_actions),
        "invented_decisions": invented_dec, "invented_actions": invented_act,
        "control_decisions": control_dec, "supported_extras": supported,
        "traps_by_kind": dict(traps), "unusable": unusable,
        "wall_p50_s": percentile(walls, 0.5), "wall_p90_s": percentile(walls, 0.9),
        "model_p50_s": percentile(models, 0.5), "model_p90_s": percentile(models, 0.9),
    }


def bar(reps: list[dict], local: bool) -> dict:
    checks = {
        "core recall >= 90%": all((r["core_recall"] or 0) >= CORE_BAR for r in reps),
        "invented decisions <= 1": all(r["invented_decisions"] <= INVENTED_BAR for r in reps),
        "no unusable summaries": all(r["unusable"] == 0 for r in reps),
    }
    if local:
        checks["p90 model time <= 180 s"] = all(r["model_p90_s"] is not None and r["model_p90_s"] <= P90_BAR for r in reps)
    return {"checks": checks, "pass": all(checks.values())}


def collect() -> dict[str, list[list[tuple[dict, dict, dict]]]]:
    blind_map = json.loads((common.RESULTS / "blind-map.json").read_text())
    rows = {c: {(r["meeting"], r["rep"]): r for r in common.read_jsonl(common.RESULTS / c / "results.jsonl")}
            for c in common.CONTESTANTS}
    by = {c: [[], []] for c in common.CONTESTANTS}
    for path in sorted((common.RESULTS / "judgments").glob("m*.json")):
        j = json.loads(path.read_text())
        meeting = j["meeting"]
        key = common.load_key(meeting)
        for letter, grade in j["grades"].items():
            contestant, rep = blind_map[meeting][letter]
            by[contestant][rep].append((key, grade, rows[contestant][(meeting, rep)]))
    return by


def pct(v):
    return "—" if v is None else f"{v * 100:.1f}%"


def secs(v):
    return "—" if v is None else f"{v:.0f} s"


def report(scores: dict) -> str:
    names = list(scores)
    lines = ["# Meeting summary bench — report", "",
             "Generated by `bench/score.py`. Two reps per contestant; cells show rep 0 / rep 1.", "",
             "| | " + " | ".join(names) + " |", "|---|" + "---|" * len(names)]

    def row(label, fn):
        lines.append(f"| {label} | " + " | ".join(" / ".join(fn(r) for r in scores[n]["reps"]) for n in names) + " |")

    row("Core recall (decisions + actions)", lambda r: pct(r["core_recall"]))
    row("Decision recall", lambda r: pct(r["decision_recall"]))
    row("Action recall", lambda r: pct(r["action_recall"]))
    row("Owner accuracy", lambda r: pct(r["owner_accuracy"]))
    row("Open-question recall", lambda r: pct(r["question_recall"]))
    row("**Invented decisions** (incl. traps)", lambda r: str(r["invented_decisions"]))
    row("Invented action items (incl. traps)", lambda r: str(r["invented_actions"]))
    row("Decisions listed in control meetings", lambda r: str(r["control_decisions"]))
    row("Extra items the transcript supports", lambda r: str(r["supported_extras"]))
    row("Unusable summaries", lambda r: str(r["unusable"]))
    row("Wall time p50 / p90", lambda r: f"{secs(r['wall_p50_s'])}, {secs(r['wall_p90_s'])}")
    row("Model time p50 / p90", lambda r: f"{secs(r['model_p50_s'])}, {secs(r['model_p90_s'])}")
    lines += ["", "## Traps fallen for, by kind (both reps)", ""]
    kinds = sorted({k for n in names for r in scores[n]["reps"] for k in r["traps_by_kind"]})
    lines += ["| Kind | " + " | ".join(names) + " |", "|---|" + "---|" * len(names)]
    for k in kinds:
        lines.append(f"| {k} | " + " | ".join(str(sum(r["traps_by_kind"].get(k, 0) for r in scores[n]["reps"])) for n in names) + " |")
    lines += ["", "## Bar (both reps must pass every check)", ""]
    for n in names:
        b = scores[n]["bar"]
        verdict = "PASSES" if b["pass"] else "does not pass"
        lines.append(f"- **{n}: {verdict}** — " + "; ".join(f"{c}: {'yes' if ok else 'no'}" for c, ok in b["checks"].items()))
    return "\n".join(lines) + "\n"


def main() -> int:
    by = collect()
    scores = {}
    for contestant, reps in by.items():
        rep_scores = [score_rep(entries) for entries in reps]
        scores[contestant] = {"reps": rep_scores, "bar": bar(rep_scores, local=contestant in LOCAL)}
    (common.RESULTS / "scores.json").write_text(json.dumps(scores, indent=1))
    (common.RESULTS / "REPORT.md").write_text(report(scores))
    print(report(scores))
    return 0


if __name__ == "__main__":
    sys.exit(main())
